import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ParentSize from "@visx/responsive/lib/components/ParentSize";
import PieChart from '../components/Pie';
import { GradientPinkBlue } from '@visx/gradient';
import { AreaClosed } from '@visx/shape';
import { makeStyles } from '@material-ui/core/styles';
import Paper from '@material-ui/core/Paper';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>visx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ParentSize>
          {({ width, height }) => 
          <div>
          {/* <GradientPinkBlue id="gradient" /> */}
          <PieChart width={width} height={height} />
          </div>
          }
        </ParentSize>
        {/* <PieChart/> */}
        <svg>
          {/* <AreaClosed fill="url('#gradient')" /> */}
          {/* <rect width={100} height={100} fill="url('#gradient')"></rect> */}
        </svg>
      </div>
    </div>
  )
}
